### ISSUE TITLE
Stream fails to play inside iOS PWA application

### ISSUE THREAD

**Issue by rubenkuipers** [Dynamsoft/barcode-reader-javascript#133]
We are having an issue where the video stream of the scanner implemented in a PWA on iOS Safari fails to load. It seems this has been a known issue.

A member of this [bugreport](https://bugs.webkit.org/show_bug.cgi?id=252465) forum mentions he's been in contact with your team to figure out this issue in the past. Do you know if this issue has been resolved in the latest iOS version? And if so, what are the nessesary steps we need to take to make sure this will be resolved?

Currently we're on version **9.2.13** of the SDK.

**Comment by rubenkuipers** [comment]
@Keillion Any news regarding this issue?

**Comment by Keillion** [comment]
This bug seems to be fixed. @Cube-J has tested it in iPhone14 Pro with iOS17.0.1.

But there is another bug in iOS. The webgl is broken in some iPhone device with iOS17.x. Some of iPhone14 pro and iPhone15 are reported.😂

Pls use the following code to workaround webgl bug:
```js
// `scanner` is the instance of `BarcodeScanner`
scanner?._dce._bWebGLSupported=false;
scanner._bUseWebgl=false;
```
We are now busy releasing a version to automatically detect and workaround this issue.

Therefore, keep using [singleFrameMode](https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/api-reference/BarcodeScanner.html#singleframemode) as a fallback. Apple always surprises us again one day. 🤷‍♂️

**Comment by Keillion** [comment]
Since Cube has tested on iOS17 and this problem no longer recurs, we close it.
